// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Lsp6U_yNKvQ6abzmoXU_4t5YOG3syaM',
    appId: '1:172118463747:web:b223f8e2b9890c72ca4536',
    messagingSenderId: '172118463747',
    projectId: 'puppysfun-5ff68',
    authDomain: 'puppysfun-5ff68.firebaseapp.com',
    storageBucket: 'puppysfun-5ff68.appspot.com',
    measurementId: 'G-ZTBXMFF638',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdpTfObA8YzNtnGUGJCcUqSSzgIqeASfA',
    appId: '1:172118463747:android:b9f88bb586b032b9ca4536',
    messagingSenderId: '172118463747',
    projectId: 'puppysfun-5ff68',
    storageBucket: 'puppysfun-5ff68.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBvES0rKipRclIeQEYMQIh4weAo7FmCsg',
    appId: '1:172118463747:ios:c9471dcc1cfbbbf1ca4536',
    messagingSenderId: '172118463747',
    projectId: 'puppysfun-5ff68',
    storageBucket: 'puppysfun-5ff68.appspot.com',
    iosClientId: '172118463747-idbaof747o5buq9gkaqpb31p7dji4h5j.apps.googleusercontent.com',
    iosBundleId: 'funs.puppys.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBvES0rKipRclIeQEYMQIh4weAo7FmCsg',
    appId: '1:172118463747:ios:d1ed3feffeef72ddca4536',
    messagingSenderId: '172118463747',
    projectId: 'puppysfun-5ff68',
    storageBucket: 'puppysfun-5ff68.appspot.com',
    iosClientId: '172118463747-v4r5kglsom7o0jkc1nscifn61ie12el0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterPuppysfun',
  );
}
